### ISSUE TITLE
Need to update to v2.4.0 and above

### ISSUE THREAD

**Issue by balazsnemeth** [gamedevgarage/gamedevgarage_obfuscator#1]
Thank you for this script, we investigated whether to include these in our project or not. Finaly, we decided not to include it, keep reading:

The script is written in a way that if the MD5 hash is turned on the WebMobile build process, it does not find the project.js. This is not an issue anymore, because CocosCreator v2.4.0 has the bundles instead of src/project.js file. 

1. To updated for CocosCreator v2.4.0 we initialize `mainJsPath` as:
```
  // find the main project file in the main bundle
  var mainBundle = options.bundles.find(function(bundle) {return bundle.name === 'main';});
  var mainJsPath = path.join(mainBundle.dest, '/index.js'); 
 ...
```

The rest of the script does work.

Finally, we obfuscated main bundle index js, which contains all of our code. BUT, as it is stated in javascript-obfuscator's github: " the obfuscated code is 15-80% slower (depends on options) and the files are significantly larger." And it is very true, our 415KB js file turned to 1.234 KB and the performance also dropped a bit.

So we turned down the idea of using additional obfuscation for now. Let us know if you think we mad a bad decision.

**Comment by gamedevgarage** [comment]
Thanks for the contribution.
There are some options can be applied during obfuscation. In that way file size and performance wil not be affected that much.
Finally it's a personal preference to obfuscate or not.

**Comment by gamedevgarage** [comment]
Updated based on your fix.
